name: "nps"
num_epochs: 1000
learning_rate: 0.001
weight_decay: 0
batch_size: 4
gradient_clipping: False
early_stopping_intervals: 100

support_size: 3
query_size: 30

hidden_representation_size: 128
n_hidden_layers: 3
hidden_size: 128
dropout_rate: 0.1
is_classifier: True

train_data_path: data/nps/train
val_data_path: data/nps/val
test_data_path: data/nps/test